import ShellLayout from '@features/shell/ShellLayout';
import { heroSlides } from '@features/write/heroSlides';

const AboutRoute = () => {
  return (
    <ShellLayout
      activeTab="about"
      title="About i-typed-this"
      description="The recorder, playback, and analysis tool turns accusations into portable evidence students can carry anywhere."
    >
      <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm" data-testid="about-route">
        <div>
          <p className="text-xs uppercase tracking-[0.3em] text-slate-500">Why it exists</p>
          <h2 className="mt-2 text-2xl font-semibold text-slate-900">False positives need receipts</h2>
        </div>
        <p className="text-sm text-slate-600">
          AI detectors can wrongly flag work up to 78% of the time. i-typed-this captures the keystroke story—pauses, revisions,
          and pastes—so a student can unzip proof instead of debating a probability score.
        </p>
        <ul className="grid gap-2 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-600 sm:grid-cols-3">
          <li className="font-semibold text-slate-900">Record · private, in-browser tracking</li>
          <li className="font-semibold text-slate-900">Replay · show how the draft formed</li>
          <li className="font-semibold text-slate-900">Analyse · identify authentic writing patterns</li>
        </ul>
      </section>

      <section className="grid gap-6 md:grid-cols-2">
        {heroSlides.map((slide) => (
          <article
            key={slide.id}
            id={`about-${slide.id}`}
            className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"
          >
            <div className="space-y-1">
              <p className="text-xs uppercase tracking-[0.25em] text-slate-500">{slide.eyebrow}</p>
              <h3 className="text-2xl font-semibold text-slate-900">{slide.title}</h3>
              <p className="text-sm text-slate-600">{slide.intro}</p>
            </div>
            {slide.screenshotSrc ? (
              <img
                src={slide.screenshotSrc}
                alt={slide.screenshotAlt}
                className="w-full rounded-2xl border border-slate-200 shadow-sm"
              />
            ) : null}
            <ol className="list-decimal space-y-2 pl-5 text-sm text-slate-700">
              {slide.steps.map((step, index) => (
                <li key={`${slide.id}-step-${index}`}>{step}</li>
              ))}
            </ol>
            {slide.result ? <p className="text-sm font-semibold text-slate-900">{slide.result}</p> : null}
            {slide.footnote ? <p className="text-xs italic text-slate-500">{slide.footnote}</p> : null}
          </article>
        ))}
      </section>

      <section className="grid gap-6 md:grid-cols-2">
        <article className="flex flex-col justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="space-y-3">
            <p className="text-xs uppercase tracking-[0.25em] text-slate-500">🚀 Get in touch</p>
            <h3 className="text-2xl font-semibold text-slate-900">Shape the future with feedback</h3>
            <p className="text-sm text-slate-600">
              Found this useful? Got a feature request? Managed to fool the analyser? I&rsquo;d love to hear from you. I&rsquo;m looking for
              teachers and students who can test a trial and help guide the next set of features.
            </p>
            <p className="text-sm text-slate-600">
              Currently building for institutions: batch upload student files, straight-forward submission portals, and
              autogenerated comprehension questions so reviewers can focus on teaching the nuance.
            </p>
            <ul className="list-disc space-y-1 pl-5 text-sm text-slate-600">
              <li>Batch loading student files for review.</li>
              <li>A simple portal for student submissions.</li>
              <li>Comprehension questions generated from each essay.</li>
            </ul>
          </div>
          <a
            href="mailto:i.typed.this.contact@gmail.com?subject=Feedback%20for%20i-typed-this"
            className="inline-flex items-center justify-center rounded-full border border-slate-200 bg-slate-900 px-5 py-2 text-sm font-semibold text-white transition hover:bg-slate-700"
          >
            Send an Email
          </a>
        </article>

        <article className="flex flex-col justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="space-y-3">
            <p className="text-xs uppercase tracking-[0.25em] text-slate-500">💖 Support this project</p>
            <h3 className="text-2xl font-semibold text-slate-900">Help keep it growing</h3>
            <p className="text-sm text-slate-600">
              Every donation offsets development and server costs. If you can, make a contribution to a good cause in the name
              of this project or support the tool directly.
            </p>
            <div className="flex flex-wrap gap-3">
              <a
                href="https://www.justgiving.com/page/i-typed-this"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center justify-center rounded-full border border-slate-200 bg-slate-900 px-5 py-2 text-sm font-semibold text-white transition hover:bg-slate-700"
              >
                ❤️ Donate to Save the Children
              </a>
              <a
                href="https://buymeacoffee.com/itypedthis"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center justify-center rounded-full border border-slate-200 bg-slate-900/80 px-5 py-2 text-sm font-semibold text-white transition hover:bg-slate-700"
              >
                ☕ Buy me a coffee
              </a>
            </div>
          </div>
          <div className="text-xs text-slate-500">
            Thank you for keeping evidence-based tutoring tools free and focused on real students.
          </div>
        </article>
      </section>
    </ShellLayout>
  );
};

export default AboutRoute;
